// packages/vite-server/src/views/HomeView.tsx
import { useAtom } from 'jotai'
import { useCounter, useLocalStorage } from '@/hooks'
import { counterAtom, themeWithPersistenceAtom } from '@/store'

export default function HomeView() {
  const { count, increment, decrement, reset } = useCounter(0)
  const [jotaiCount, setJotaiCount] = useAtom(counterAtom)
  const [theme, setTheme] = useAtom(themeWithPersistenceAtom)
  const [name, setName] = useLocalStorage('name', 'Guest')

  const toggleTheme = () => {
    setTheme(theme === 'light' ? 'dark' : 'light')
  }

  return (
    <div className="home">
      <h1>Welcome to Vite Server</h1>
      <p>Learn Vite dev server configuration!</p>

      <div className="section">
        <h2>Local State Counter</h2>
        <p>Count: {count}</p>
        <button onClick={increment}>+</button>
        <button onClick={decrement}>-</button>
        <button onClick={reset}>Reset</button>
      </div>

      <div className="section">
        <h2>Jotai State Counter</h2>
        <p>Count: {jotaiCount}</p>
        <button onClick={() => setJotaiCount((c) => c + 1)}>+</button>
        <button onClick={() => setJotaiCount((c) => c - 1)}>-</button>
        <button onClick={() => setJotaiCount(0)}>Reset</button>
      </div>

      <div className="section">
        <h2>Theme (persisted)</h2>
        <p>Current theme: {theme}</p>
        <button onClick={toggleTheme}>Toggle Theme</button>
      </div>

      <div className="section">
        <h2>Local Storage Hook</h2>
        <input
          value={name}
          onChange={(e) => setName(e.target.value)}
          placeholder="Enter your name"
        />
        <p>Hello, {name}!</p>
      </div>
    </div>
  )
}

// packages/vite-basic/src/views/HomeView.vue
<template>
  <div class="home">
    <h1>Welcome to Vite Basic</h1>
    <HelloWorld msg="Hello Vue 3 + Vite" />
    <div class="counter-section">
      <h2>Counter Example</h2>
      <p>Count: {{ count }}</p>
      <button @click="increment">+</button>
      <button @click="decrement">-</button>
      <button @click="reset">Reset</button>
    </div>
    <div class="theme-section">
      <h2>Theme Example</h2>
      <p>Current theme: {{ theme }}</p>
      <button @click="toggleTheme">Toggle Theme</button>
    </div>
  </div>
</template>

<script setup lang="ts">
import HelloWorld from '@/components/HelloWorld.vue'
import { useCounter, useTheme } from '@/composables'

const { count, increment, decrement, reset } = useCounter(0)
const { theme, toggleTheme } = useTheme()
</script>

<style scoped>
.home {
  padding: 20px;
}

.counter-section,
.theme-section {
  margin-top: 40px;
}

button {
  margin: 0 5px;
  padding: 8px 16px;
  cursor: pointer;
}
</style>
